#!/bin/bash

# input the positive integer n
echo -n "Enter a Positive Integer:"
read Num

# define first two element, and then calculate the Fibonacci by iterative method (using loop)
f1=1
f2=1

echo "The Fibonacci sequence for the number $Num is : "

# loop start here
for (( i=1;i<=Num;i++ ))
do
echo -n "$f1 "
fn=$((f1+f2))
f1=$f2
f2=$fn
done

# print the number
echo
